# Site
repository: Godrl/godrl.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김현기
title: 웹,앱 개발자
email: gusrl0515@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# SNS
github_username: Godrl
# stackoverflow_username: "00000001"
# flickr_username: jekyll
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#  - title: itsgoingto.be
#    icon: fas fa-globe
#    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Ruby on Rails 기반의 2년차 웹 개발자이며,
  현재 Flutter & Dart 기반의 하이브리드앱 개발중입니다.


content:
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Language
        quote: >
        description: |
          - ES6
          - Ruby, Python
          - Dart
      - layout: left
        title: Framework
        quote: >
        description: |
          - Vuejs
          - Rails, Django
          - Flutter
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 13hz
        sub_title: 웹,하이브리드앱 개발
        caption: 2020.10 ~ 현재
        quote: >
        description: |
          - API 개발
          - 하이브리드앱 설계 및 개발
          - 인앱브라우저에서 외부브라우저 호출처리
          - Quill Editor 커스터마이징
#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag